--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022. 03. 28. 10:58:18
-- Server version: 5.5.5-10.4.18-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE seriesdatabase;

--
-- Drop table `comment`
--
DROP TABLE IF EXISTS comment;

--
-- Drop table `favorite`
--
DROP TABLE IF EXISTS favorite;

--
-- Drop table `series`
--
DROP TABLE IF EXISTS series;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE seriesdatabase;

--
-- Create table `user`
--
CREATE TABLE user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  userName VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  `E-mail` VARCHAR(255) DEFAULT NULL,
  permission INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `series`
--
CREATE TABLE series (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) DEFAULT NULL,
  `Release` VARBINARY(255) DEFAULT NULL,
  ageLimit VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `favorite`
--
CREATE TABLE favorite (
  id INT(11) NOT NULL AUTO_INCREMENT,
  userId INT(11) DEFAULT NULL,
  seriesId INT(11) DEFAULT NULL,
  Watched VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE favorite 
  ADD CONSTRAINT FK_favorite_series_id FOREIGN KEY (seriesId)
    REFERENCES series(id);

--
-- Create foreign key
--
ALTER TABLE favorite 
  ADD CONSTRAINT FK_favorite_user_id FOREIGN KEY (userId)
    REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create table `comment`
--
CREATE TABLE comment (
  id INT(11) NOT NULL AUTO_INCREMENT,
  userId INT(11) DEFAULT NULL,
  comment VARCHAR(255) DEFAULT NULL,
  seriesId INT(11) DEFAULT NULL,
  ratePoint INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE comment 
  ADD CONSTRAINT FK_comment_series_id FOREIGN KEY (seriesId)
    REFERENCES series(id) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Create foreign key
--
ALTER TABLE comment 
  ADD CONSTRAINT FK_comment_user_id FOREIGN KEY (userId)
    REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'Admin', 'AdminPassword', 'Admin@gmail.com', 1),
(2, 'User#234', 'UserPassword#234', 'User#234@gmail.com', 2),
(3, 'User#235', 'UserPassword#235', 'User#235@gmail.com', 2);

-- 
-- Dumping data for table series
--
INSERT INTO series VALUES
(1, 'The Last Kingdom', x'32303135', '16'),
(2, 'Vikings', x'32303133', '16'),
(3, 'Game of Thrones', x'32303131', '18');

-- 
-- Dumping data for table favorite
--
INSERT INTO favorite VALUES
(1, 2, 3, 'watched'),
(2, 3, 1, 'in progress');

-- 
-- Dumping data for table comment
--
INSERT INTO comment VALUES
(1, 2, 'I not like this', 1, 5),
(2, 2, 'Not bad', 3, 3);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;